#!/usr/bin/env bash

declare -x APACHE_HOSTNAME
: "${APACHE_HOSTNAME:="${HOSTNAME}"}"

declare -x APACHE_PORT
: "${APACHE_PORT:="8080"}"

declare -x APACHE_WEBROOT
: "${APACHE_WEBROOT:="/srv/www"}"

declare -x APACHE_SERVER_TOKENS
: "${APACHE_SERVER_TOKENS:="Prod"}"

declare -x APACHE_SERVER_SIGNATURE
: "${APACHE_SERVER_SIGNATURE:="Off"}"

declare -x APACHE_TRACE_ENABLE
: "${APACHE_TRACE_ENABLE:="Off"}"

declare -x APACHE_COMBINED_FORMAT
: "${APACHE_COMBINED_FORMAT:="combinedio"}"

declare -x APACHE_PROXY_FORMAT
: "${APACHE_PROXY_FORMAT:="proxyio"}"

declare -x APACHE_SKIP_TEMPLATES
: "${APACHE_SKIP_TEMPLATES:="false"}"

declare -x APACHE_SKIP_CHOWN
: "${APACHE_SKIP_CHOWN:="false"}"

declare -x APACHE_HEALTHCHECK_URL
: "${APACHE_HEALTHCHECK_URL:="http://localhost:${APACHE_PORT}/"}"

declare -x APACHE_HEALTHCHECK_CODE
: "${APACHE_HEALTHCHECK_CODE:="200"}"
