FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:ba3a77a41ae5e164a9ffeb1a116d3a963e942e7a88d95bc40ff8b2f9967565f4

VOLUME ["/etc/apache2/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 apache && \
  useradd -u 1000 -d /srv/www -g apache -s /bin/bash -M apache && \
  apk add apache2 apache2-webdav apache2-utils apache2-icons apache2-error mailcap && \
  rm -rf /var/cache/apk/* /etc/apache2/*

COPY ./overlay /
