FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:5b037c077d4ba74ae7da3a97e0f4a5caff892dfae63bc2ca2f9053a46f6c40d7

VOLUME ["/etc/apache2/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 apache && \
  useradd -u 1000 -d /srv/www -g apache -s /bin/bash -M apache && \
  apk add apache2 apache2-webdav apache2-utils apache2-icons apache2-error mailcap && \
  rm -rf /var/cache/apk/* /etc/apache2/*

COPY ./overlay /
