FROM webhippie/alpine:latest-arm64@sha256:0e8f1ef77ac6d03dd3ec413ef5072157a719b7f0bdb01c8c5cf3f138198422dd

VOLUME ["/etc/apache2/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 apache && \
  useradd -u 1000 -d /srv/www -g apache -s /bin/bash -M apache && \
  apk add apache2 apache2-webdav apache2-utils apache2-icons apache2-error mailcap && \
  rm -rf /var/cache/apk/* /etc/apache2/*

COPY ./overlay /
