FROM webhippie/alpine:latest-arm@sha256:78cdd9f057caff4ee9e3f53bd231b506c47bc2a51bc69167bd9abdea1b0ed549

VOLUME ["/etc/apache2/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 apache && \
  useradd -u 1000 -d /srv/www -g apache -s /bin/bash -M apache && \
  apk add apache2 apache2-webdav apache2-utils apache2-icons apache2-error mailcap && \
  rm -rf /var/cache/apk/* /etc/apache2/*

COPY ./overlay /
