#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

if [ -d ./custom.d ]
then
  for FILE in $(find ./custom.d -type f -iname *.sh | sort)
  do
    source ${FILE}
  done
fi

pushd ${APACHE_WEBROOT} > /dev/null
  echo "> starting apache service"
  exec /usr/sbin/httpd -DFOREGROUND
popd > /dev/null
