#!/bin/bash
source /usr/bin/entrypoint

echo "> writing apache config"
/usr/bin/templater -d -p apache -o /etc/apache2/httpd.conf /etc/templates/httpd.conf.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

echo "> writing host config"
/usr/bin/templater -d -p apache -o /etc/apache2/host.conf /etc/templates/host.conf.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

echo "> chown webroot files"
find /srv/www \( \! -user apache -o \! -group apache \) -print0 | xargs -0 -r chown apache:apache
