#!/bin/bash
source /usr/bin/entrypoint

if [[ "${APACHE_SKIP_TEMPLATES}" != "true" ]]
then
  echo "> writing apache config"
  /usr/bin/gomplate -V \
    -o /etc/apache2/httpd.conf \
    -f /etc/templates/httpd.conf.tmpl

  if [[ $? -ne 0 ]]
  then
    /bin/s6-svscanctl -t /etc/s6
    exit 1
  fi

  echo "> writing host config"
  /usr/bin/gomplate -V \
    -o /etc/apache2/host.conf \
    -f /etc/templates/host.conf.tmpl

  if [[ $? -ne 0 ]]
  then
    /bin/s6-svscanctl -t /etc/s6
    exit 1
  fi
fi

if [[ "${APACHE_SKIP_CHOWN}" != "true" ]]
then
  echo "> chown webroot files"
  find ${APACHE_WEBROOT} \( \! -user apache -o \! -group apache \) -print0 | xargs -0 -r chown apache:apache
fi

